name: TimeLogger
version: ${project.version}
main: com.mctng.timelogger.TimeLogger
api-version: 1.13
depend: []
authors: [Worf2340]
website: www.mctng.com

commands:
  playtime:
    usage: /playtime [player] <time> OR /playtime [player] since [date] OR /playtime [player] from [date] [time] to [date] [time]
    permission: timelogger.playtime
  playtimelb:
    usage: /playtimelb OR /playtimelb
    permission: timelogger.playtimelb
    aliases: [playtimeleaderboard]

permissions:
  timelogger.playtime:
    description: Allow all /playtime commands.
    default: op
  timelogger.playtimelb:
    description: Allow /playtimelb command.
    default: op
  timelogger.playtimelb.custom:
    description: Allow all /playtimelb commands.
    default: op
    children:
      timelogger.playtimelb: true


